project:
  type: website

website:
  title: "edwards-gitpage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

