---
title: "Tutorials summary"
---

It's easy to collect programming tutorials and links to cool packages. Here I keep a running list, and summarize the ones I've looked at. While I intend this mostly for my own purposes, hopefully it's helpful to you.

# Not yet explored

## Tutorials

-   [Navarro's very detailed "statistics with R" course-turned-book ](https://learningstatisticswithr.com/)
-   [Observable JS](https://quarto.org/docs/computations/ojs.html#overview). This is the link for the quarto guide for getting started in Observable, but it's something I'd like to learn period. Currently unread
-   [R in VSCode](https://medium.com/analytics-vidhya/a-fresh-start-for-r-in-vscode-ec61ed108cf6). I'm pretty happy with Rstudio/Posit
-   [beautiful tables in R](https://rfortherestofus.com/2019/11/how-to-make-beautiful-tables-in-r/) -[Debugging R code](https://rstats.wtf/debugging-r-code.html). It'd be useful to review debugging tools.
-   [workflow management sofware in ecology](https://aquaticdatasciopensci.github.io/day2-bigdata/). Talks about Targets and such.
-   [Arrow for R](https://www.youtube.com/watch?v=DAJO7h2TYX0)
-   [walkthrough on data scientist pipeline](https://www.business-science.io/careers/2022/03/15/the-data-science-career-path.html). Not convinced about the specifics, or the opinions. But (a) may be useful for me if I decide on a non-academic path, and (b) may be useful for me if I stay on the academic path and mentor folks.
-   [dolt](https://docs.dolthub.com/concepts/dolt/sql) An SQL tool

## Packages

-   [Shiny editor walkthrough](https://www.youtube.com/watch?v=gYPnLiudtGU) -[targets package](https://books.ropensci.org/targets/). This is something that is likely to be important with the big multi-species project.
-   [ggdensity](https://www.business-science.io/code-tools/2022/07/21/ggdensity-plot-high-density.html?utm_content=bufferf7ce7&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer). Note that the tutorial seems to be calling these "high-density region", but I'd probably want to check the technical definition (is this based on k-nearest neighbors? KDE?).
-   tidy models
-   plotly
-   data.table (for fast work with big data) and dtplyr for working with.
-   dbplyr for working with databases.
-   furr (for parallel processing with purrr)
-   sparklyr (cloud computing with R)
-   disk.frame (working with big data locally)

## Informative twitter threads

-   [academic job applications](https://twitter.com/ViktoriaWagner1/status/1556308008573050882)
-   [quarto and observable](https://twitter.com/Mayacelium/status/1553195852692238336)
-   [academic practices for industry](https://twitter.com/Melterialsgal/status/1553141674540294145)

## Other

-   [Eliza Grames' butterfly risk shiny app, for inspiration](https://elizagrames.shinyapps.io/butterflyRisk/)
-   [Machine learning and dynamic models?](https://sinews.siam.org/Details-Page/dynamics-based-machine-learning-for-nonlinearizable-phenomena)
-   [Interview with a consulting statistician](https://sinews.siam.org/Details-Page/a-conversation-with-mathematical-consultant-john-d-cook)
-   [communities in data article in siam](https://sinews.siam.org/Details-Page/communities-in-data)
-   [Boosting creativity](https://sinews.siam.org/Details-Page/how-to-boost-your-creativity) (siam article).
-   https://storyset.com/ free customizable illustrations
-   https://iconmonstr.com/ free icons
-   [Firth correction for logistic regression](https://journals.lww.com/epidem/Abstract/2021/09000/Decreased_Susceptibility_of_Marginal_Odds_Ratios.5.aspx) Is this something I need to worry about?

# Explored

## Tutorials

## Packages

## Informative twitter threads

-   [Thread on giving talks](https://twitter.com/bioinfo_mark/status/1554969205270728704). I don't agree with the opening statement that of 100 PI talks, 99 of them will be poor. (I think I might see 30 talks at a larger conference, so that means about every three conferences I see one good talk?). Lots of good info and philosophy on giving good talks, though. Pieces of it match what I've been taught before, or resonate.

# Data sources to explore

-   [USGS data repository](https://www.sciencebase.gov/catalog/)
